/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScaleListCellRenderer.java
 *
 * Created on 21.03.2010, 19:32:57
 */
package at.motriv.gui;

import at.motriv.datamodel.entities.scale.Scale;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import org.openide.util.NbBundle;

/**
 *
 * @author wolfi
 */
public class ScaleListCellRenderer extends JPanel implements ListCellRenderer
{

  private static final long serialVersionUID = 1L;

  /** Creates new form ScaleListCellRenderer */
  public ScaleListCellRenderer()
  {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lbName = new javax.swing.JLabel();
    lbScale = new javax.swing.JLabel();
    lbTrack = new javax.swing.JLabel();

    setLayout(new java.awt.GridLayout());

    lbName.setText(org.openide.util.NbBundle.getMessage(ScaleListCellRenderer.class, "ScaleListCellRenderer.lbName.text")); // NOI18N
    add(lbName);

    lbScale.setText(org.openide.util.NbBundle.getMessage(ScaleListCellRenderer.class, "ScaleListCellRenderer.lbScale.text")); // NOI18N
    add(lbScale);

    lbTrack.setText(org.openide.util.NbBundle.getMessage(ScaleListCellRenderer.class, "ScaleListCellRenderer.lbTrack.text")); // NOI18N
    add(lbTrack);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel lbName;
  private javax.swing.JLabel lbScale;
  private javax.swing.JLabel lbTrack;
  // End of variables declaration//GEN-END:variables

  @Override
  public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
  {
    if (value instanceof Scale) {
      Scale scale = (Scale) value;
      lbName.setText(scale.getName());
      lbScale.setText(NbBundle.getMessage(getClass(), "ScaleListCellRenderer.lbScale.text", scale.getScale()));
      lbTrack.setText(NbBundle.getMessage(getClass(), "ScaleListCellRenderer.lbTrack.text", scale.getTrackWidth()));
    } else {
      lbName.setText(null);
      lbScale.setText(null);
      lbTrack.setText(null);
    }
//    if (value==list.getSelectedValue()) {
//      lbName.setForeground(list.getSelectionForeground());
//      lbName.setBackground(list.getSelectionBackground());
//      lbScale.setForeground(list.getSelectionForeground());
//      lbScale.setBackground(list.getSelectionBackground());
//      lbTrack.setForeground(list.getSelectionForeground());
//      lbTrack.setBackground(list.getSelectionBackground());
//    } else {
//      lbName.setForeground(list.getForeground());
//      lbName.setBackground(list.getBackground());
//      lbScale.setForeground(list.getForeground());
//      lbScale.setBackground(list.getBackground());
//      lbTrack.setForeground(list.getForeground());
//      lbTrack.setBackground(list.getBackground());
//    }
    return this;
  }
}
