/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseContactPanel.java
 *
 * Created on 10.04.2010, 14:45:09
 */
package at.motriv.gui.contact;

import at.motriv.datamodel.entities.contact.Contact;
import at.motriv.datamodel.entities.contact.ContactType;
import at.motriv.gui.contact.model.ChooseContactTableModel;
import at.motriv.gui.contact.model.SearchState;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author wolfi
 */
public class ChooseContactPanel extends JPanel implements PropertyChangeListener, DocumentListener, ListSelectionListener
{

  private static final long serialVersionUID = 1L;
  public static final String PROP_SELECTION = "selection";
  private final ChooseContactTableModel tableModel = new ChooseContactTableModel();

  /** Creates new form ChooseContactPanel */
  public ChooseContactPanel()
  {
    initComponents();
    tableModel.addPropertyChangeListener(ChooseContactTableModel.PROP_SEARCHSTATE, this);
    jTextField1.getDocument().addDocumentListener(this);
    jTable1.getSelectionModel().addListSelectionListener(this);
  }

  public void setFilter(ContactType filter)
  {
    tableModel.setContactFilter(filter);
  }

  public void resetFilter()
  {
    jTextField1.setText(null);
  }

  public Contact getSelectedContact()
  {
    if (jTable1.getSelectedRow() != -1) {
      return tableModel.getValueAt(jTable1.getSelectedRow());
    }
    return null;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    jLabel1.setText(org.openide.util.NbBundle.getMessage(ChooseContactPanel.class, "ChooseContactPanel.jLabel1.text")); // NOI18N

    jTable1.setModel(tableModel);
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(1, 1, 1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

  @Override
  public void propertyChange(PropertyChangeEvent evt)
  {
    if (ChooseContactTableModel.PROP_SEARCHSTATE.equals(evt.getPropertyName())) {
      jTable1.setEnabled(tableModel.getSearchState()==SearchState.SEARCH_FINISHED);
    }
  }

  @Override
  public void insertUpdate(DocumentEvent e)
  {
    tableModel.setFilter(jTextField1.getText());
  }

  @Override
  public void removeUpdate(DocumentEvent e)
  {
    tableModel.setFilter(jTextField1.getText());
  }

  @Override
  public void changedUpdate(DocumentEvent e)
  {
    tableModel.setFilter(jTextField1.getText());
  }

  @Override
  public void valueChanged(ListSelectionEvent e)
  {
    firePropertyChange(PROP_SELECTION, null, getSelectedContact());
  }
}
