/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.motriv.gui.contact.wizard;

import java.awt.event.ItemEvent;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JPanel;
import org.openide.util.NbBundle;

public final class NewContactVisualPanel1 extends JPanel 
{

  private static final long serialVersionUID = 1L;
  private CreationMode selection;
  private Set<CreationMode> allowedModes;

  /** Creates new form NewContactVisualPanel1 */
  public NewContactVisualPanel1()
  {
    initComponents();
  }

  public void setAllowedModes(Set<CreationMode> allowedModes)
  {
    this.allowedModes = Collections.unmodifiableSet(new HashSet<CreationMode>(allowedModes));
    jRadioButton1.setEnabled(this.allowedModes.contains(CreationMode.NEW_MANUFACTURER));
    jRadioButton2.setEnabled(this.allowedModes.contains(CreationMode.NEW_RETAILER));
    jRadioButton3.setEnabled(this.allowedModes.contains(CreationMode.NEW_MANUFACTURER_FROM_RETAILER));
    jRadioButton4.setEnabled(this.allowedModes.contains(CreationMode.NEW_RETAILER_FROM_MANUFACTURER));
    setSelection(getSelection());
  }

  public CreationMode getSelection()
  {
    return selection;
  }

  private CreationMode calcSelection()
  {
    if (jRadioButton1.isSelected()) {
      return CreationMode.NEW_MANUFACTURER;
    } else if (jRadioButton2.isSelected()) {
      return CreationMode.NEW_RETAILER;
    } else if (jRadioButton3.isSelected()) {
      return CreationMode.NEW_MANUFACTURER_FROM_RETAILER;
    } else if (jRadioButton4.isSelected()) {
      return CreationMode.NEW_RETAILER_FROM_MANUFACTURER;
    }
    return null;
  }

  public void setSelection(CreationMode mode)
  {
    CreationMode old = selection;
    jRadioButton1.setSelected(jRadioButton1.isEnabled() && mode == CreationMode.NEW_MANUFACTURER);
    jRadioButton2.setSelected(jRadioButton2.isEnabled() && mode == CreationMode.NEW_RETAILER);
    jRadioButton3.setSelected(jRadioButton3.isEnabled() && mode == CreationMode.NEW_MANUFACTURER_FROM_RETAILER);
    jRadioButton4.setSelected(jRadioButton4.isEnabled() && mode == CreationMode.NEW_RETAILER_FROM_MANUFACTURER);
    selection = calcSelection();
    if (old != selection) {
      firePropertyChange("selection", old, selection);
    }
  }

  @Override
  public String getName()
  {
    return NbBundle.getMessage(getClass(),"NewContactWizard.step1.name");
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton3 = new javax.swing.JRadioButton();
    jRadioButton4 = new javax.swing.JRadioButton();

    buttonGroup1.add(jRadioButton1);
    org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(NewContactVisualPanel1.class, "NewContactVisualPanel1.jRadioButton1.text")); // NOI18N
    jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButton1ItemStateChanged(evt);
      }
    });

    buttonGroup1.add(jRadioButton2);
    org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(NewContactVisualPanel1.class, "NewContactVisualPanel1.jRadioButton2.text")); // NOI18N
    jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButton1ItemStateChanged(evt);
      }
    });

    buttonGroup1.add(jRadioButton3);
    org.openide.awt.Mnemonics.setLocalizedText(jRadioButton3, org.openide.util.NbBundle.getMessage(NewContactVisualPanel1.class, "NewContactVisualPanel1.jRadioButton3.text")); // NOI18N
    jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButton1ItemStateChanged(evt);
      }
    });

    buttonGroup1.add(jRadioButton4);
    org.openide.awt.Mnemonics.setLocalizedText(jRadioButton4, org.openide.util.NbBundle.getMessage(NewContactVisualPanel1.class, "NewContactVisualPanel1.jRadioButton4.text")); // NOI18N
    jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jRadioButton1ItemStateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jRadioButton1)
          .addComponent(jRadioButton2)
          .addComponent(jRadioButton3)
          .addComponent(jRadioButton4))
        .addContainerGap(30, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jRadioButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jRadioButton4)
        .addContainerGap(24, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jRadioButton1ItemStateChanged
  {//GEN-HEADEREND:event_jRadioButton1ItemStateChanged
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      setSelection(calcSelection());
    }
  }//GEN-LAST:event_jRadioButton1ItemStateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JRadioButton jRadioButton4;
  // End of variables declaration//GEN-END:variables

}

