/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContactPanel.java
 *
 * Created on 06.04.2010, 21:53:40
 */
package at.motriv.gui.contact;

import at.motriv.datamodel.entities.contact.Contact;
import at.motriv.gui.contact.model.ContactCountryComboBoxModel;
import at.motriv.gui.helper.ChangeDocumentListener;
import java.awt.Desktop;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import org.openide.util.Exceptions;

/**
 *
 * @author wolfi
 */
public class ContactPanel extends javax.swing.JPanel implements PropertyChangeListener
{

  private static final long serialVersionUID = 1L;
  public static final String PROP_MODIFIED = "modified";
  public static final String PROP_DATAVALID = "dataValid";
  private DirtyMutableContact builder;
  private final ContactCountryComboBoxModel countryModel = new ContactCountryComboBoxModel();

  /** Creates new form ContactPanel */
  public ContactPanel()
  {
    initComponents();
    initChangeListener();
    countryModel.refresh();
  }

  public boolean isModified()
  {
    return builder.isDirty();
  }

  public boolean isDataValid()
  {
    return builder.isValid();
  }

  public DirtyMutableContact getBuilder()
  {
    return builder;
  }

  public Contact getContact()
  {
    return builder.build();
  }

  public void setContact(Contact builder)
  {
    if (this.builder != null) {
      this.builder.removePropertyChangeListener(this);
    }
    this.builder = new DirtyMutableContact(builder);
    this.builder.addPropertyChangeListener(this);
    assignValues();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbName = new javax.swing.JLabel();
    lbAddress = new javax.swing.JLabel();
    lbCity = new javax.swing.JLabel();
    lbCountry = new javax.swing.JLabel();
    lbPhone1 = new javax.swing.JLabel();
    lbPhone2 = new javax.swing.JLabel();
    lbFax = new javax.swing.JLabel();
    lbEmail = new javax.swing.JLabel();
    lbWWW = new javax.swing.JLabel();
    lbMemo = new javax.swing.JLabel();
    edName = new javax.swing.JTextField();
    edAddress = new javax.swing.JTextField();
    edAddress2 = new javax.swing.JTextField();
    edZip = new javax.swing.JTextField();
    cbCountry = new javax.swing.JComboBox();
    edEmail = new javax.swing.JTextField();
    edWWW = new javax.swing.JTextField();
    edPhone1 = new javax.swing.JTextField();
    edPhone2 = new javax.swing.JTextField();
    edFax = new javax.swing.JTextField();
    btWWW = new javax.swing.JButton();
    btMail = new javax.swing.JButton();
    edCity = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    edMemo = new javax.swing.JEditorPane();
    btShop = new javax.swing.JButton();
    lbShop = new javax.swing.JLabel();
    edShop = new javax.swing.JTextField();

    lbName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbName.setLabelFor(edName);
    lbName.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbName.text")); // NOI18N

    lbAddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbAddress.setLabelFor(edAddress);
    lbAddress.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbAddress.text")); // NOI18N

    lbCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbCity.setLabelFor(edZip);
    lbCity.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbCity.text")); // NOI18N

    lbCountry.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbCountry.setLabelFor(cbCountry);
    lbCountry.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbCountry.text")); // NOI18N

    lbPhone1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbPhone1.setLabelFor(edPhone1);
    lbPhone1.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbPhone1.text")); // NOI18N

    lbPhone2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbPhone2.setLabelFor(edPhone2);
    lbPhone2.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbPhone2.text")); // NOI18N

    lbFax.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbFax.setLabelFor(edFax);
    lbFax.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbFax.text")); // NOI18N

    lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbEmail.setLabelFor(edEmail);
    lbEmail.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbEmail.text")); // NOI18N

    lbWWW.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbWWW.setLabelFor(edWWW);
    lbWWW.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbWWW.text")); // NOI18N

    lbMemo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbMemo.setLabelFor(edMemo);
    lbMemo.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbMemo.text")); // NOI18N

    edName.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edName.text")); // NOI18N

    edAddress.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edAddress.text")); // NOI18N

    edAddress2.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edAddress2.text")); // NOI18N

    edZip.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edZip.text")); // NOI18N

    cbCountry.setEditable(true);
    cbCountry.setModel(countryModel);

    edEmail.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edEmail.text")); // NOI18N
    edEmail.getDocument().addDocumentListener(new ChangeDocumentListener(){
      protected void changed(DocumentEvent evt) {
        emailChanged(evt);
      }
    });

    edWWW.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edWWW.text")); // NOI18N
    edWWW.getDocument().addDocumentListener(new ChangeDocumentListener(){
      protected void changed(DocumentEvent evt) {
        wwwChanged(evt);
      }
    });

    edPhone1.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edPhone1.text")); // NOI18N

    edPhone2.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edPhone2.text")); // NOI18N

    edFax.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edFax.text")); // NOI18N

    btWWW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/motriv/gui/contact/icon_world.gif"))); // NOI18N
    btWWW.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btWWW.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btWWWActionPerformed(evt);
      }
    });

    btMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/motriv/gui/contact/icon_email.gif"))); // NOI18N
    btMail.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btMail.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btMailActionPerformed(evt);
      }
    });

    edCity.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edCity.text")); // NOI18N

    jScrollPane1.setViewportView(edMemo);

    btShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at/motriv/gui/contact/icon_world.gif"))); // NOI18N
    btShop.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btShop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btShopActionPerformed(evt);
      }
    });

    lbShop.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    lbShop.setLabelFor(edShop);
    lbShop.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.lbShop.text")); // NOI18N

    edShop.setText(org.openide.util.NbBundle.getMessage(ContactPanel.class, "ContactPanel.edShop.text")); // NOI18N
    edShop.getDocument().addDocumentListener(new ChangeDocumentListener(){
      protected void changed(DocumentEvent evt) {
        shopChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lbPhone1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
              .addComponent(lbPhone2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
              .addComponent(lbShop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbWWW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lbFax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbMemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addComponent(edPhone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addComponent(edPhone2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addComponent(edFax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
              .addComponent(lbCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(edAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addComponent(edAddress2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(edZip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edCity, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
              .addComponent(cbCountry, 0, 319, Short.MAX_VALUE)
              .addComponent(edName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(edWWW, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                  .addComponent(edEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(btMail)
                  .addComponent(btWWW)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(edShop, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btShop)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(edName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbName))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbAddress)
          .addComponent(edAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(edAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbCity)
          .addComponent(edZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(edCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbCountry))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(edEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbEmail))
          .addComponent(btMail))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(edWWW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbWWW))
          .addComponent(btWWW))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(edShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbShop))
          .addComponent(btShop))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbPhone1)
          .addComponent(edPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbPhone2)
          .addComponent(edPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(edFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbFax))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lbMemo))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btMailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btMailActionPerformed
  {//GEN-HEADEREND:event_btMailActionPerformed
    URI uri = getEmailURI();
    if (uri != null && getCanEmail()) {
      try {
        Desktop.getDesktop().mail(uri);
      } catch (IOException ex) {
        Exceptions.printStackTrace(ex);
      }
    }
  }//GEN-LAST:event_btMailActionPerformed

  private void btWWWActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btWWWActionPerformed
  {//GEN-HEADEREND:event_btWWWActionPerformed
    URI uri = getWWWURI();
    if (uri != null && getCanWWW()) {
      try {
        Desktop.getDesktop().browse(uri);
      } catch (IOException ex) {
        Exceptions.printStackTrace(ex);
      }
    }
  }//GEN-LAST:event_btWWWActionPerformed

  private void btShopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btShopActionPerformed
  {//GEN-HEADEREND:event_btShopActionPerformed
    URI uri = getShopURI();
    if (uri != null && getCanWWW()) {
      try {
        Desktop.getDesktop().browse(uri);
      } catch (IOException ex) {
        Exceptions.printStackTrace(ex);
      }
    }
  }//GEN-LAST:event_btShopActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btMail;
  private javax.swing.JButton btShop;
  private javax.swing.JButton btWWW;
  private javax.swing.JComboBox cbCountry;
  private javax.swing.JTextField edAddress;
  private javax.swing.JTextField edAddress2;
  private javax.swing.JTextField edCity;
  private javax.swing.JTextField edEmail;
  private javax.swing.JTextField edFax;
  private javax.swing.JEditorPane edMemo;
  private javax.swing.JTextField edName;
  private javax.swing.JTextField edPhone1;
  private javax.swing.JTextField edPhone2;
  private javax.swing.JTextField edShop;
  private javax.swing.JTextField edWWW;
  private javax.swing.JTextField edZip;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lbAddress;
  private javax.swing.JLabel lbCity;
  private javax.swing.JLabel lbCountry;
  private javax.swing.JLabel lbEmail;
  private javax.swing.JLabel lbFax;
  private javax.swing.JLabel lbMemo;
  private javax.swing.JLabel lbName;
  private javax.swing.JLabel lbPhone1;
  private javax.swing.JLabel lbPhone2;
  private javax.swing.JLabel lbShop;
  private javax.swing.JLabel lbWWW;
  // End of variables declaration//GEN-END:variables

  private void assignValues()
  {
    edName.setText(builder.getName());
    edAddress.setText(builder.getAddress1());
    edAddress2.setText(builder.getAddress2());
    edZip.setText(builder.getZip());
    edCity.setText(builder.getCity());
    cbCountry.setSelectedItem(builder.getCountry());
    edEmail.setText(builder.getEmail());
    edWWW.setText(builder.getWWW());
    edShop.setText(builder.getShopAddress());
    edPhone1.setText(builder.getPhone1());
    edPhone2.setText(builder.getPhone2());
    edFax.setText(builder.getFax());
    edMemo.setText(builder.getMemo());
  }

  private void emailChanged(DocumentEvent evt)
  {
    if (builder != null) {
      builder.setEmail(edEmail.getText());
    }
    btMail.setEnabled(getEmailURI() != null && getCanEmail());
  }

  private boolean getCanEmail()
  {
    return Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.MAIL);
  }

  private URI getEmailURI()
  {
    try {
      URI uri = new URI("mailto", edEmail.getText(), null);
      return uri;
    } catch (URISyntaxException ex) {
      //Exceptions.printStackTrace(ex);
    }
    return null;
  }

  private void wwwChanged(DocumentEvent evt)
  {
    if (builder != null) {
      builder.setWWW(edWWW.getText());
    }
    btWWW.setEnabled(getWWWURI() != null && getCanWWW());
  }

  private void shopChanged(DocumentEvent evt)
  {
    if (builder != null) {
      builder.setShopAddress(edShop.getText());
    }
    btShop.setEnabled(getShopURI() != null && getCanWWW());
  }

  private URI getWWWURI()
  {
    try {
      String str = edWWW.getText();
      URI uri;
      if (str.toLowerCase().startsWith("http://")) {
        uri = new URI(str);
      } else {
        uri = new URI("http", str, null);
      }
      return uri;
    } catch (URISyntaxException ex) {
    }
    return null;
  }

  private URI getShopURI()
  {
    try {
      String str = edShop.getText();
      URI uri;
      if (str.toLowerCase().startsWith("http://")) {
        uri = new URI(str);
      } else {
        uri = new URI("http", str, null);
      }
      return uri;
    } catch (URISyntaxException ex) {
    }
    return null;
  }

  private boolean getCanWWW()
  {
    return Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE);
  }

  @Override
  public void propertyChange(final PropertyChangeEvent evt)
  {
    if ("valid".equals(evt.getPropertyName())) {
      if (SwingUtilities.isEventDispatchThread()) {
        firePropertyChange(PROP_DATAVALID, evt.getOldValue(), evt.getNewValue());
      } else {
        SwingUtilities.invokeLater(new Runnable()
        {

          @Override
          public void run()
          {
            firePropertyChange(PROP_DATAVALID, evt.getOldValue(), evt.getNewValue());
          }
        });
      }
    } else if ("dirty".equals(evt.getPropertyName())) {
      if (SwingUtilities.isEventDispatchThread()) {
        firePropertyChange(PROP_MODIFIED, evt.getOldValue(), evt.getNewValue());
      } else {
        SwingUtilities.invokeLater(new Runnable()
        {

          @Override
          public void run()
          {
            firePropertyChange(PROP_MODIFIED, evt.getOldValue(), evt.getNewValue());
          }
        });
      }
    }
  }

  private void initChangeListener()
  {
    edAddress.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setAddress1(edAddress.getText());
        }
      }
    });
    edAddress2.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setAddress2(edAddress2.getText());
        }
      }
    });
    edCity.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setCity(edCity.getText());
        }
      }
    });
    edFax.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setFax(edFax.getText());
        }
      }
    });
    edMemo.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setMemo(edMemo.getText());
        }
      }
    });
    edName.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setName(edName.getText());
        }
      }
    });
    edPhone1.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setPhone1(edPhone1.getText());
        }
      }
    });
    edPhone2.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setPhone2(edPhone2.getText());
        }
      }
    });
    edZip.getDocument().addDocumentListener(new ChangeDocumentListener()
    {

      @Override
      protected void changed(DocumentEvent e)
      {
        if (builder != null) {
          builder.setZip(edZip.getText());
        }
      }
    });
  }
}
